[build]
  command = "CI= yarn build"  # Replace this with your build command
  ignore_warnings = true     # Disable treating warnings as errors
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200